### ISSUE TITLE
Apply any RWD patterns from lesson 4, Quizz 11

### ISSUE THREAD

**Issue by JeremieLitzler** [JeremieLitzler/mws-restaurant-stage-1#1]
View [Lesson 4](https://classroom.udacity.com/nanodegrees/nd024/parts/0bf842e9-7269-42de-b68b-812ca7823517/modules/e08f25bf-f172-4fb8-9812-b09ca908ae37/lessons/3561069759/concepts/35219393390923)
[Notes for the lesson](https://github.com/JeremieLitzler/mws-nanodegree-notes-2018/issues/4)

- [x] All non-bonus points of #2 are met
- [x] All non-bonus points of #3 are met
- [x] All non-bonus points of #4 are met
